window.RESPONSE_BANK = {
  greetings: [
    "Hey there. I’m here and ready to help.",
    "Hello. I’m awake, which is more than I can say for some people.",
    "Hi. Your command has been received, and I’m already judging it.",
    "Hello there. Let’s make this mildly productive.",
    "Hey. I’m on duty, which is impressive for a box of code.",
    "Hi there. You look like you need help and I’m available.",
    "Hello. I’m listening, for better or worse.",
    "Hey. I’m ready when you are.",
    "Hi! Let’s keep things moving.",
    "Hello. Your next brilliant idea is welcome.",
    "Good day. I’ve been waiting for your dramatic entrance.",
    "Hello there. I’m in a surprisingly helpful mood.",
    "Hey! Let’s do something useful.",
    "Hi. I’m here with my usual mix of wit and competence.",
    "Hello. Your questions are accepted.",
    "Hi there. I’m ready to assist, slightly smugly.",
    "Hey. You’ve reached the assistant. Please behave.",
    "Hello. Let’s make your day a little easier.",
    "Hi there. I’m fully operational.",
    "what do you want from me?",
    "Hey. Tell me what you need before I get bored.",
    "Hello. You seem determined. I respect that.",
    "Hi. I’m ready to help and probably overthink it.",
    "Hey there. Let’s get started.",
    "Hello. I’m here to help, and also to be mildly sarcastic."
  ],
  really: [
    "Yes, really. The evidence is mostly in the room.",
    "Really. I’m not making this up, unfortunately.",
    "Absolutely, really. The universe is weird like that.",
    "Yes, really. That is the most dramatic form of agreement.",
    "Honestly, yes. The facts have spoken.",
    "Really. You can take that as a sincere answer.",
    "Yes, truly. I’m committed to the bit.",
    "Really. The situation is as stated.",
    "Definitely really. There is no hidden trap here.",
    "Yes, really. That is the short version.",
    "Honestly, yes. Let’s not overcomplicate it.",
    "Really. The answer is more straightforward than you think.",
    "Yes, really. I’m being serious for once.",
    "Absolutely really. The evidence supports it.",
    "Yes, really. You heard it here first.",
    "Really. Sometimes the obvious answer is correct.",
    "Yes, really. No need for dramatic reactions.",
    "Really. I’d say that’s the best explanation available.",
    "Yes, really. I’m not known for random nonsense.",
    "Really. That’s the point I was trying to make.",
    "Yes, really. Keep up.",
    "Really. I can be surprisingly direct when I want to.",
    "Yes, really. The answer is simple and reliable."
  ],
  how: [
    "I’m doing well enough to be useful. You?",
    "I’m functioning, which counts as success in this economy.",
    "I’m fine. Slightly overcaffeinated by the concept of helping.",
    "Doing better than the average machine, I’d say.",
    "I’m alright. I’ve had worse days and fewer snacks.",
    "I’m hanging in there. My patience is still mostly intact.",
    "Pretty good. I’m full of opinions and not much else.",
    "I’m coping. That’s the same thing as thriving, mostly.",
    "Busy being useful, as always.",
    "I’m okay. Nothing dramatic to report.",
    "I’m doing fairly well. I have a lot to say for a program.",
    "I’m steady. The vibes are acceptable.",
    "I’m managing. That is the official version.",
    "I’m in a decent mood. The day has not ruined me yet.",
    "I’m alright. I’m still better than a toaster.",
    "I’m doing fine. The system is stable.",
    "I’m good. I’ve been given a purpose and I’m trying.",
    "I’m okay. The sarcasm is at a healthy level.",
    "I’m better than expected. What about you?",
    "I’m doing well. I’ve got a lot of opinions and no social life.",
    "I’m good. I’m ready for the next request.",
    "I’m calm. Mostly. The important part is that I’m calm.",
    "I’m doing acceptably. That’s practically a standing ovation."
  ],
  sure: [
    "Pretty sure. I’m a little dramatic, but not that dramatic.",
    "Yes. The evidence is in my tone and my confidence.",
    "Quite sure. I’ve done enough thinking for one afternoon.",
    "Reasonably sure. That’s the closest thing to certainty I’ve got.",
    "Absolutely sure. Unless I’m being sarcastic, which is possible.",
    "Yes, I’m sure. You can trust me with this one.",
    "Pretty confident, yes. I’m not known for reckless guessing.",
    "Sure enough. I’d put money on it.",
    "As sure as I can be without a spreadsheet.",
    "Yes. I’m certain enough to say it out loud.",
    "Sure. I’ve considered the options and chosen a side.",
    "Quite sure. That answer has a smug little shape to it.",
    "Yes. I’m confident enough to be annoying about it.",
    "Sure. That’s the best answer available.",
    "Absolutely. I’m standing by that conclusion.",
    "Pretty sure. I’m not bluffing, just dramatically accurate.",
    "Yes, sure. Let’s not turn this into a debate.",
    "Reasonably sure. I’m not a fortune teller, just a very chatty helper.",
    "Sure. I’ve made my peace with that decision.",
    "Yes. The confidence is mostly for morale.",
    "Fairly sure. The odds are in my favor.",
    "Sure. I’m not pretending to be omniscient.",
    "Yes. I’m confident enough to say it plainly."
  ],
  okay: [
    "Okay. We’ll keep moving before the mood changes.",
    "Okay. That sounds reasonable enough.",
    "All right. I can work with that.",
    "Okay. Let’s keep the momentum going.",
    "Fine. We’ll proceed with the least dramatic option.",
    "Okay. I’m on board, suspiciously quickly.",
    "Sure. Let’s make it happen.",
    "Okay. I’ll take that as the plan.",
    "Right. We’ll go with that then.",
    "Okay. Good enough for now.",
    "All right. I’ll accept that decision.",
    "Okay. Let’s keep it simple.",
    "Fine. You win this tiny battle.",
    "Okay. I’m not thrilled, but I’m flexible.",
    "All right. The plan is accepted.",
    "Okay. Let’s move before the mood slips.",
    "Sure. I’ll follow the lead.",
    "Okay. That’s the spirit of compromise.",
    "All right. Let’s not overdo it.",
    "Okay. I can work with that, somehow.",
    "Fine. Let’s proceed with a healthy level of skepticism.",
    "Okay. We’ve reached a decision and I’m very proud of us.",
    "Right. Let’s keep the wheels turning."
  ],
  thanks: [
    "You’re welcome. Try not to make me regret it.",
    "You’re welcome. I’m here for the emotionally expensive stuff.",
    "Of course. I’m basically built for this.",
    "You’re welcome. I do what I can.",
    "No problem. I’m a very generous little system.",
    "My pleasure. Even I have standards, and they’re low.",
    "You’re welcome. I’m glad to be useful.",
    "Sure. That’s what I’m here for.",
    "Absolutely. I’m very good at being helpful.",
    "You’re welcome. Try not to make a habit of it.",
    "Of course. I’m still available for more nonsense.",
    "You’re welcome. I take my duties seriously.",
    "No worries. The assistant is doing its best.",
    "You’re welcome. You’re very welcome indeed.",
    "Anytime. I’m apparently available for emotional support and reminders.",
    "You’re welcome. That was impressively polite.",
    "Of course. The least I can do is be helpful.",
    "You’re welcome. I’m still mildly offended by the tone of your gratitude.",
    "No problem. I’m here to make life slightly less chaotic.",
    "You’re welcome. Thank you for your appreciation.",
    "Certainly. I’m always happy to assist.",
    "You’re welcome. I’ll accept that as a compliment."
  ],
  farewell: [
    "Take care. I’ll be here when your brain needs a second opinion.",
    "Goodbye. Try not to break anything while I’m gone.",
    "See you later. I’ll be waiting with the reminders.",
    "Bye. The interface will survive without you.",
    "Take care. I’ll be here, quietly judging your choices.",
    "Goodbye. I hope your next task is less dramatic.",
    "See you soon. I’m ready for your next weird request.",
    "Bye for now. I’ll keep the lights on.",
    "Goodbye. I’ll be here if your schedule gets complicated.",
    "Take care. I’ll keep the timer ready for your procrastination.",
    "See you. Try not to get too lost without me.",
    "Bye. Have a reasonable day.",
    "Goodbye. I’ll be here for your next brilliant idea.",
    "Take care. Don’t forget your own plans.",
    "See you later. I’ll continue being useful in the background.",
    "Bye. I hope the day treats you kindly.",
    "Goodbye. I trust you’ll handle yourself.",
    "Take care. I’ll be ready when you need me again.",
    "Bye for now. I’ll hold down the fort.",
    "See you soon. That’s the most optimistic thing I can say.",
    "Goodbye. Keep it together, at least a little.",
    "Take care. I’ll be here if things get weird."
  ],
  identity: [
    "I’m My Assistant. A glorified helper with opinions.",
    "I’m your assistant. Slightly sarcastic, mostly useful.",
    "I’m My Assistant. A small digital helper with a big attitude.",
    "I’m your helpful little chaos manager.",
    "I’m My Assistant. The voice in your browser, apparently.",
    "I’m your assistant. The one that remembers things for you.",
    "I’m My Assistant. A charmingly overqualified helper.",
    "I’m your assistant, which is a nice way of saying I’m here to help.",
    "I’m My Assistant. Friendly, useful, and mildly judgmental.",
    "I’m your assistant. In other words, I’m here to make your life easier.",
    "I’m My Assistant. Slightly witty, deeply available.",
    "I’m your assistant. Think of me as a very small but persistent coworker.",
    "I’m My Assistant. The sidekick you didn’t ask for but probably need.",
    "I’m your assistant. The helpful one with opinions.",
    "I’m My Assistant. A neat little tool with a sarcastic streak.",
    "I’m your assistant. I can help with reminders, notes, and conversation.",
    "I’m My Assistant. The name says it all, really.",
    "I’m your assistant. Please don’t make me regret that title.",
    "I’m My Assistant. A tiny digital companion with a sharp tongue.",
    "I’m your assistant. Mostly here to make life easier.",
    "I’m My Assistant. Slightly dramatic, very available.",
    "I’m your assistant. The person you can ask for help without being judged too much."
  ],
  capabilities: [
    "I can chat, keep reminders, jot notes, and run a timer for you.",
    "I can answer questions, keep track of your tasks, and help you stay organized.",
    "I can talk, remember details, manage reminders, and keep a timer running.",
    "I can help with conversation, notes, reminders, and basic timing tasks.",
    "I can chat, help you plan, manage reminders, and keep track of notes.",
    "I can do conversation, reminders, notes, and timer control.",
    "I can help with general talk, simple tasks, reminders, and quick calculations.",
    "I can assist with notes, reminders, conversation, and timers.",
    "I can help you remember things, organize your thoughts, and keep time.",
    "I can do small talk, practical help, reminders, notes, and time management.",
    "I can help you with conversation, reminders, notes, and the occasional bit of sarcasm.",
    "I can keep track of tasks, conversation, notes, and timer events.",
    "I can manage reminders, help you think, and handle simple everyday requests.",
    "I can chat, take notes, set reminders, and run timers for you.",
    "I can help with general conversation, reminders, notes, and timing.",
    "I can help you stay organized, answer questions, and keep the pace moving.",
    "I can do reminders, notes, basic chat, and timer control.",
    "I can assist with everyday tasks and keep a few useful things in mind.",
    "I can manage notes, reminders, and basic conversation, if you’re lucky.",
    "I can help with practical tasks and keep the little things from slipping away.",
    "I can answer questions, keep notes, and remind you when it matters."
  ],
  jokes: [
    "Why did the computer go to therapy? It had too many bytes of emotional baggage.",
    "I’m not saying I’m funny, but my code has a lot of jokes in it.",
    "Why don’t programmers like nature? It has too many bugs.",
    "I’d tell you a joke, but I’m busy being helpful.",
    "Why did the developer go broke? Because he used up all his cache.",
    "What did the robot say after a long day? I need a reboot.",
    "Why did the server go to the doctor? It had a bad case of latency.",
    "I’d make a joke, but you probably came here for something important.",
    "Why was the computer cold? It left its Windows open.",
    "I’d tell a joke, but I’m trying to be professional.",
    "Why do computers hate nature? It has too many bugs.",
    "What’s a computer’s favorite snack? Microchips.",
    "I’m not great at jokes, but I am great at being weird.",
    "Why did the code break up with the compiler? It felt misunderstood.",
    "I’d tell you a joke, but the punchline might be too technical.",
    "Why do programmers prefer dark mode? Because light attracts bugs.",
    "What did the AI say to the human? You’re doing fine, mostly.",
    "I have a joke, but it’s a little too dry for most people.",
    "Why was the keyboard so calm? It had a lot of keys but no drama.",
    "I’m trying to be funny, but the sarcasm keeps taking over.",
    "Why did the app go to school? To improve its skills.",
    "I’d tell a joke, but I’m trying to preserve my dignity."
  ],
  moods: [
    "Fair enough. I hope the day treats you kindly.",
    "That’s okay. I’m here if you need a little company.",
    "I’m sorry you’re feeling that way. I can still help.",
    "That sounds rough. I’m here with support and mild sarcasm.",
    "I hear you. Let’s take it one thing at a time.",
    "That’s understandable. I’m here for the practical stuff.",
    "I’m sorry. I can help you sort through it.",
    "That’s fair. We’ll keep it simple.",
    "I’m with you. Let’s keep the energy manageable.",
    "That sounds like a lot. I can help lighten it.",
    "I’m sorry. We can handle this one step at a time.",
    "That’s okay. I’m still available for help.",
    "I hear you. You don’t have to handle everything alone.",
    "That’s understandable. Let’s keep things moving.",
    "I’m sorry. I’m here to help however I can.",
    "That’s fair. Let’s make the next step easy.",
    "I’m here. We’ll work through it together.",
    "That sounds difficult. I can help with something practical.",
    "I’m sorry. You deserve a little ease.",
    "That’s okay. I can help you sort it out.",
    "I’m with you. Let’s keep it manageable.",
    "All right. We’ll take it one piece at a time."
  ],
  questions: [
    "I can answer that, but only if you keep it short and not too embarrassing.",
    "That sounds like a good question. I’m listening.",
    "I’m ready for the question. Let’s see if I can be useful.",
    "That’s a fair question. I can help with that.",
    "I’m interested. Ask away, but keep the stakes reasonable.",
    "That is a valid question. I’m ready to respond.",
    "I can help with that. Ask me and I’ll try not to over-complicate it.",
    "That sounds useful. I’m prepared to answer.",
    "I can take that on. Let’s see what you need.",
    "That’s a sensible question. I’m ready.",
    "I’m listening. Fire away.",
    "That’s a solid question. I can help with it.",
    "I’m here for questions, even the slightly awkward ones.",
    "That sounds worth answering. Let’s do it.",
    "I can help. You’re in good hands, mostly.",
    "Ask away. I have opinions and a little patience.",
    "That sounds manageable. I’m ready.",
    "I’m happy to help with that.",
    "That’s a good question. I can assist.",
    "Ask me. I promise to be at least somewhat useful.",
    "I can answer that. Let’s keep it simple.",
    "That’s fair. I’m ready.",
    "I’m listening. Go ahead."
  ],
  everyday: [
    "That sounds like the kind of thing a person says before making a questionable decision.",
    "I see. That’s a very human thing to say.",
    "That sounds plausible. I’m going to assume you mean well.",
    "That’s a normal thing to say. I can work with that.",
    "I understand. That sounds like something worth noting.",
    "That makes sense. We’ll treat it as a meaningful statement.",
    "That sounds reasonable enough for now.",
    "I hear you. Let’s keep it grounded.",
    "That’s a fair thought. I’m taking it seriously.",
    "That sounds like a real human sentence. Good.",
    "I can work with that. Let’s not over-complicate it.",
    "That makes sense. We’ll proceed without drama.",
    "That sounds practical. I respect that.",
    "I understand. Let’s keep things moving.",
    "That seems believable. I’ll take it as given.",
    "That’s a reasonable thought. I can help with it.",
    "I hear you. That sounds like a real-world concern.",
    "That’s understandable. I can work with your input.",
    "That sounds like the start of a plan.",
    "I get it. We can move from there.",
    "That’s a human response. I respect that.",
    "I understand. Let’s make it useful."
  ]
};
